package fi.haagahelia.Bookstore;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.junit4.SpringRunner;

import fi.haagahelia.Bookstore.domain.User;
import fi.haagahelia.Bookstore.domain.UserRepository;

@RunWith(SpringRunner.class)
@DataJpaTest
public class UserRepositoryTest {

	@Autowired
	private UserRepository userRepo;
	
	@Test
	public void userIdAutoGenerated() {
		User user = new User("snow.john", "password", "snow.john@test", "USER");
		userRepo.save(user);
		assertThat(user.getId()).isNotNull();
	}
	
	@Test
	public void findByUsernameShouldReturnUser() {
		User user = userRepo.findByUsername("user");
		assertThat(user.getRole()).isEqualTo("USER");
	}
}
